# Generated by Django 6.0.4 on 2026-04-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(db_column='price', max_length=200),
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='overview',
        ),
    ]
